### ISSUE TITLE
When Active, ObjectInputRestriction Breaks Text Inputs

### ISSUE THREAD

**Issue by josh-palan** [ThomasKeil/pimcore-plugin-ObjectInputRestriction#1]
After I installed this plugin, I went to my class definitions and attempted to look at a text input field. No information is shown and I get the following error in php.log:

`[Thu Jul 14 08:51:58 2016] [hphp] [2041:7fa5527ff700:8475:000001] [] \nFatal error: Uncaught exception 'Exception' with message 'Call to undefined method getFirstname in class Pimcore\\Model\\User\\Folder' in /var/www/pimcore/pimcore/lib/Pimcore/Model/AbstractModel.php:273\nStack trace:\n#0 /var/www/pimcore/plugins/ObjectInputRestriction/controllers/SettingsController.php(31): Pimcore\\Model\\AbstractModel->__call()\n#1 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ObjectInputRestriction_SettingsController->getdataAction()\n#2 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch()\n#3 /var/www/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()\n#4 /var/www/pimcore/pimcore/lib/Pimcore.php(260): Zend_Controller_Front->dispatch()\n#5 /var/www/pimcore/index.php(18): Pimcore::run()\n#6 {main`

**Comment by josh-palan** [comment]
Closing as this appears to be a dead repo.
